version: '3.7'
services:
  app:
    image: hrmapp/api:v1
    ports:
      - "${PORT}:${PORT}" 
    restart: unless-stopped
    env_file: ./.env.production
    depends_on:
        - db
    networks:
      - hrmapp

  db:
    image: mysql:8.0
    container_name: db-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT}:3306" 
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DBNAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    
    restart: unless-stopped
    networks:
      - hrmapp

networks:
  hrmapp:
    driver: bridge