version: '3.7'
services:
  # app:
  #   image: tluhrmapp/api:v1
  #   volumes:
  #     - ./:/app
  #   environment: 
  #     - DB_HOST=${DB_HOST}
  #     - DB_DBNAME=${DB_DBNAME}
  #     - PORT=${PORT}
  #     - DB_PORT=${DB_PORT}
  #   ports:
  #     - "${PORT}:${PORT}" 
  #   restart: unless-stopped
  #   depends_on:
  #       - db
  #   networks:
  #     - app-tier

  db:
    image: mysql:8.0
    container_name: db-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT}:${DB_PORT}" 
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DBNAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    
    restart: unless-stopped
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge